packages:
    - coulis
    - examples/*
    - tools/*
allowBuilds:
    "@swc/core": false
    esbuild: false
    sharp: false
    unrs-resolver: false
minimumReleaseAgeExclude:
    - "@adbayb/*"
publicHoistPattern:
    - "*changesets*"
    - "*commitlint*"
    - "*eslint*"
    - "*prettier*"
    - "*turbo*"
    - "*typescript*"
    - "*types*"
