packages:
    - "examples/*"
    - "tools/*"
    - "coulis"
saveExact: true
verifyDepsBeforeRun: "warn"
update:
    githubActions: true
minimumReleaseAgeExclude:
    - "@adbayb/*"
    - "quickbundle"
    - "termost"
publicHoistPattern:
    - "*changesets*"
    - "*commitlint*"
    - "*oxfmt*"
    - "*oxlint*"
    - "*turbo*"
    - "*typescript*"
    - "*types*"
allowBuilds:
    "@swc/core": true
    esbuild: true
    sharp: true
