import type { ClassName, ScopeKey } from "../types";

import { createCache } from "./cache";
import type { Cache } from "./cache";
import { createStyleSheet } from "./stylesheet";
import type { StyleSheet } from "./stylesheet";

/**
 * The order is important. Global properties has a lesser specificity than (<) shorthand ones:
 * global < shorthand < longhand < conditional-shorthand < conditional-longhand properties.
 */
const INSERTION_ORDER_BY_SCOPE = Object.freeze({
	conditionalLonghand: 4,
	conditionalShorthand: 3,
	global: 0,
	longhand: 2,
	shorthand: 1,
});

export type Scope = {
	cache: Cache;
	commit: (params: {
		key: string;
		createRules: (className: string) => string[];
	}) => ClassName;
	styleSheet: StyleSheet;
};

const createScopes = () => {
	// eslint-disable-next-line @typescript-eslint/consistent-type-assertions
	const scopes = {} as Record<ScopeKey, Scope>;

	const scopeKeys = (
		Object.keys(INSERTION_ORDER_BY_SCOPE) as ScopeKey[]
	).sort((a, b) => {
		return INSERTION_ORDER_BY_SCOPE[a] - INSERTION_ORDER_BY_SCOPE[b];
	});

	for (const scopeKey of scopeKeys) {
		scopes[scopeKey] = createScope(scopeKey);
	}

	return scopes;
};

/**
 * Aggregate to scope and manage invariants for a given coulis instance.
 * @param key - The scope key representing the targetted style.
 * @returns Cache, stylesheet instances and methods.
 * @example
 *  createScope("global");
 */
const createScope = (key: ScopeKey): Scope => {
	const styleSheet = createStyleSheet(key);
	const cache = createCache(styleSheet);

	return {
		cache,
		commit(params) {
			const className = hash(params.key);

			if (cache.has(className)) return className;

			const rules = params.createRules(className);

			for (const rule of rules) {
				styleSheet.commit(className, rule);
			}

			cache.add(className);

			return className;
		},
		styleSheet,
	};
};

const hash = (str: string) => {
	// hash content based with FNV-1a algorithm:
	const FNVOffsetBasis = 2166136261;
	const FNVPrime = 16777619;
	let hashedValue = FNVOffsetBasis;

	for (let i = 0; i < str.length; i++) {
		hashedValue ^= str.charCodeAt(i);
		hashedValue *= FNVPrime;
	}

	// We convert hashed value to 32-bit unsigned integer
	// via logical unsigned shift operator >>>
	const uHash = hashedValue >>> 0;

	// A coulis className is generated by prefixing with "c"
	// and converting generated hash to hexadecimal
	return `c${Number(uHash).toString(16)}`;
};

export const SCOPES = createScopes();
