/* eslint-disable sort-keys-custom-order/object-keys */
type Indexable = Record<string, boolean>;

export const IS_PROD_ENV = process.env.NODE_ENV === "production";
export const IS_BROWSER_ENV = typeof window !== "undefined";
export const NO_CLASSNAME = "";
// @note: Taken from https://raw.githubusercontent.com/facebook/react/b98adb648a27640db8467064e537b238b8c306ce/packages/react-dom/src/shared/CSSProperty.js
export const UNITLESS_PROPERTIES: Indexable = {
	animationIterationCount: true,
	borderImageOutset: true,
	borderImageSlice: true,
	borderImageWidth: true,
	boxFlex: true,
	boxFlexGroup: true,
	boxOrdinalGroup: true,
	columnCount: true,
	columns: true,
	flex: true,
	flexGrow: true,
	flexPositive: true,
	flexShrink: true,
	flexNegative: true,
	flexOrder: true,
	gridArea: true,
	gridRow: true,
	gridRowEnd: true,
	gridRowSpan: true,
	gridRowStart: true,
	gridColumn: true,
	gridColumnEnd: true,
	gridColumnSpan: true,
	gridColumnStart: true,
	fontWeight: true,
	lineClamp: true,
	lineHeight: true,
	opacity: true,
	order: true,
	orphans: true,
	tabSize: true,
	widows: true,
	zIndex: true,
	zoom: true,
	// @section: svg properties
	fillOpacity: true,
	floodOpacity: true,
	stopOpacity: true,
	strokeDasharray: true,
	strokeDashoffset: true,
	strokeMiterlimit: true,
	strokeOpacity: true,
	strokeWidth: true,
	// @section: prefixed properties
	WebkitLineClamp: true,
};
// From PREACT:
// export const IS_NON_DIMENSIONAL = /acit|ex(?:s|g|n|p|$)|rph|grid|ows|mnc|ntw|ine[ch]|zoo|^ord/i;
export const SHORTHAND_PROPERTIES: Indexable = {
	animation: true,
	background: true,
	border: true,
	borderBottom: true,
	borderColor: true,
	borderLeft: true,
	borderRadius: true,
	borderRight: true,
	borderStyle: true,
	borderTop: true,
	borderWidth: true,
	columnRule: true,
	columns: true,
	flex: true,
	flexFlow: true,
	font: true,
	grid: true,
	gridArea: true,
	gridColumn: true,
	gridRow: true,
	gridTemplate: true,
	listStyle: true,
	margin: true,
	offset: true,
	outline: true,
	overflow: true,
	padding: true,
	placeContent: true,
	placeItems: true,
	placeSelf: true,
	textDecoration: true,
	transition: true,
};
