import { UNITLESS_PROPERTIES } from "./constants";
import type { StyleObject } from "./types";

export const hash = (str: string) => {
	// hash content based with FNV-1a algorithm:
	const FNVOffsetBasis = 2166136261;
	const FNVPrime = 16777619;
	let hashedValue = FNVOffsetBasis;

	for (let i = 0; i < str.length; i++) {
		hashedValue ^= str.charCodeAt(i);
		hashedValue *= FNVPrime;
	}

	// @note: we convert hashed value to 32-bit unsigned integer
	// via logical unsigned shift operator >>>
	const uHash = hashedValue >>> 0;

	// @note: a coulis className is generated by prefixing with "c"
	// and converting generated hash to hexadecimal
	return `c${Number(uHash).toString(16)}`;
};

export const isNumber = (value: unknown): value is number => {
	return typeof value === "number" || !Number.isNaN(Number(value));
};

export const isObject = (value: unknown): value is Record<string, unknown> => {
	return value !== null && typeof value === "object";
};

export const minify = (value: string) => {
	return value.replace(/\s{2,}|\s+(?={)|\r?\n/gm, "");
};

export const toDeclaration = (property: string, value: number | string) => {
	// @note: Anatomy of a css syntax:
	// .className { background-color: blue; color: red } = css rule-set
	// .className = selector
	// { background-color: blue; color: red } = declaration block (contains one or more declarations separated by semicolons)
	// background-color: blue = a declaration
	// background-color = property (or property name)
	// blue = value (or property value)

	// @section: from JS camelCase to CSS kebeb-case
	const normalizedProperty = property.replace(
		/([A-Z])/g,
		(matched) => `-${matched.toLowerCase()}`,
	);

	// @section: format value to follow CSS specs (unitless number)
	const normalizedValue =
		typeof value === "string" || UNITLESS_PROPERTIES[property]
			? value
			: `${value}px`;

	return `${normalizedProperty}:${normalizedValue};`;
};

export const toManyDeclaration = <S extends StyleObject>(styleObject: S) => {
	let declarationBlock = "";

	for (const property of Object.keys(styleObject)) {
		const value = styleObject[property];

		if (value) {
			declarationBlock += toDeclaration(property, value);
		}
	}

	return declarationBlock;
};
