// eslint-disable-next-line unicorn/prefer-global-this
export const IS_SERVER_ENVIRONMENT = typeof window === "undefined";

// Taken from https://raw.githubusercontent.com/facebook/react/b98adb648a27640db8467064e537b238b8c306ce/packages/react-dom/src/shared/CSSProperty.js
export const UNITLESS_PROPERTIES = new Set([
	"animationIterationCount",
	"borderImageOutset",
	"borderImageSlice",
	"borderImageWidth",
	"boxFlex",
	"boxFlexGroup",
	"boxOrdinalGroup",
	"columnCount",
	"columns",
	// SVG properties
	"fillOpacity",
	"flex",
	"flexGrow",
	"flexShrink",
	"floodOpacity",
	"fontWeight",
	"gridArea",
	"gridColumn",
	"gridColumnEnd",
	"gridColumnStart",
	"gridRow",
	"gridRowEnd",
	"gridRowStart",
	"lineClamp",
	"lineHeight",
	"opacity",
	"order",
	"orphans",
	"stopOpacity",
	"strokeDasharray",
	"strokeDashoffset",
	"strokeMiterlimit",
	"strokeOpacity",
	"strokeWidth",
	"tabSize",
	// Property prefixes
	"WebkitLineClamp",
	"widows",
	"zIndex",
	"zoom",
]);

/*
 * From PREACT:
 * export const IS_NON_DIMENSIONAL = /acit|ex(?:s|g|n|p|$)|rph|grid|ows|mnc|ntw|ine[ch]|zoo|^ord/i;
 */
export const SHORTHAND_PROPERTIES = new Set([
	"animation",
	"background",
	"border",
	"borderBottom",
	"borderColor",
	"borderLeft",
	"borderRadius",
	"borderRight",
	"borderStyle",
	"borderTop",
	"borderWidth",
	"columnRule",
	"columns",
	"flex",
	"flexFlow",
	"font",
	"grid",
	"gridArea",
	"gridColumn",
	"gridRow",
	"gridTemplate",
	"listStyle",
	"margin",
	"offset",
	"outline",
	"overflow",
	"padding",
	"placeContent",
	"placeItems",
	"placeSelf",
	"textDecoration",
	"transition",
]);
